### PR TITLE
Dockerfile to create reproducible build

### PR DESCRIPTION
**Pull request by reinvantveer**
Signed-off-by: Name <rein@vantveer.me>

Hi Ricky, thanks for sharing your awesome project. It brings together two of my hobbies: coding in Rust and retro computing.
I hacked together the outline of a Dockerfile to try and reproduce your build instructions. It almost works, except for the final Rust compilation step.

It exits with:
```
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I/llvm-project/llvm/include" "-I/llvm-m68k/include" "-std=c++14" "-fno-exceptions" "-fno-rtti" "-D_GNU_SOURCE" "-D_DEBUG" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DLLVM_COMPONENT_ASMPARSER" "-DLLVM_COMPONENT_BITREADER" "-DLLVM_COMPONENT_BITWRITER" "-DLLVM_COMPONENT_COVERAGE" "-DLLVM_COMPONENT_INSTRUMENTATION" "-DLLVM_COMPONENT_IPO" "-DLLVM_COMPONENT_LINKER" "-DLLVM_COMPONENT_LTO" "-DLLVM_COMPONENT_M68K" "-DLLVM_COMPONENT_X86" "-DNDEBUG" "-o" "/rust-m68k/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-2b8944c4df3e12e2/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp"
  cargo:warning=In file included from llvm-wrapper/PassWrapper.cpp:6:
  cargo:warning=llvm-wrapper/LLVMWrapper.h:1:10: fatal error: llvm-c/BitReader.h: No such file or directory
  cargo:warning=    1 | #include "llvm-c/BitReader.h"
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit code: 1

  --- stderr


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I/llvm-project/llvm/include" "-I/llvm-m68k/include" "-std=c++14" "-fno-exceptions" "-fno-rtti" "-D_GNU_SOURCE" "-D_DEBUG" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DLLVM_COMPONENT_ASMPARSER" "-DLLVM_COMPONENT_BITREADER" "-DLLVM_COMPONENT_BITWRITER" "-DLLVM_COMPONENT_COVERAGE" "-DLLVM_COMPONENT_INSTRUMENTATION" "-DLLVM_COMPONENT_IPO" "-DLLVM_COMPONENT_LINKER" "-DLLVM_COMPONENT_LTO" "-DLLVM_COMPONENT_M68K" "-DLLVM_COMPONENT_X86" "-DNDEBUG" "-o" "/rust-m68k/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-2b8944c4df3e12e2/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp" with args "c++" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/rust-m68k/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--features" " llvm max_level_info" "--manifest-path" "/rust-m68k/compiler/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
```
At this stage, I'm unsure where BitReader.h should come from. It appears to have been made in the LLVM compilation, but I don't know what I missed on its compilation.

Maybe you can help me out here?
Thanks, 
Rein

### CODE REVIEW

**Comment by reinvantveer** [comment]
Oh yeah and in the commit history there's some stuff trying to set up a GitHub actions workflow but that didn't fly because the runner ran out of disk space. LLVM is quite the monster.

**Comment by ricky26** [comment]
Hi, thanks for this! As far as I'm aware the llvm-c headers should just be part of the distribution and `llvm-config` should find them. I'll try and have a quick look into this later!

I might be tempted to make the Dockerfile be something like Dockerfile.toolchain to differentiate it from the Mega Drive crates but that's a minor thing to worry about later.

I hope the repository doesn't seem too quiet, I've mostly been spending time trying to upstream the changes I made to the compiler. :sweat_smile:

**Comment by reinvantveer** [comment]
Righty, added in some stuff,but couldn't get it built due to disk space requirements. Apparently, 230Gb of free disk space isn't enough to build this using Docker?

**Comment by ricky26** [comment]
> Do you set particular stock by having a release build _with_ debug info?

Ooops. no, I just have it so I can actually debug the compiler. I've updated the instructions. :sweat_smile: 

Thanks again for taking the time to get this working.

You're welcome to add instructions to the README.md, otherwise I'll happily put some notes in once this is merged.

When you're happy, feel free to mark this PR as ready for review. I've added a CONTRIBUTING.md to the project sources, referencing the DCO, you'll need to check you're happy to comply with that and add a `Signed-off-by: Name <email>` line to the top of your PR message.

**Comment by reinvantveer** [comment]
That should do it for the toolchain part, now let's see if it will compile to m68k machine code! 
The good part about having a smaller toolchain build is that it can now actually run in a GitHub actions workflow.

**Comment by reinvantveer** [comment]
The toolchain builds, but the Dockerfile isn't quite there yet. It fails on building the rust-mega-drive root crate with:
```
Step 25/29 : RUN $HOME/.cargo/bin/cargo build --release
 ---> Running in c89094bacf8d
...
   Compiling megapong v0.1.0 (/rust-mega-drive/examples/megapong)
error: language item required, but not found: `eh_personality`
```
Related? https://github.com/phil-opp/blog_os/issues/629

**Comment by reinvantveer** [comment]
Sooo close!

**Comment by reinvantveer** [comment]
Only the last step remains. There's some kind of syntactical error:
```
Step 11/11 : RUN cargo megadrive build
 ---> Running in 0cbd90724c19
error: Found argument '' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build --manifest-path <PATH> --profile <PROFILE-NAME> --target <TRIPLE>... -Z <FLAG>...

For more information try --help
Error: command ["cargo", "build", "--manifest-path", "/rust-mega-drive/examples/megapong/Cargo.toml", "-Z", "unstable-options", "-Z", "build-std=core", "--profile", "release", "--target", "m68k-none-eabi", ""] exited with code 1
```

**Comment by ricky26** [comment]
Oops, it looks like that happens if you run `cargo megadrive build` _without_ `--verbose`.

I append an extra empty arg erroneously in the non-verbose case.

**Comment by reinvantveer** [comment]
Righty, definitely making progress here, but the build is still struggling with the backend triplet. The README says `m68k-unknown-linux-gnu`, which is indeed built into rustc. I can verify using `rustc --print target-list`. It is also the only m68k target it will build: even if I specify `m68k-unknown-eabi` it will build for `m68k-unknown-linux-gnu` instead. I built in a debug step in Dockerfile.toolchain that prints the list of m68k targets, it only shows `m68k-unknown-linux-gnu`.

However.

`share/targets/m68k-none-eabi.json` mentions `m68k-none-eabi` as target, as does src/lib.rs but this target does not exist:
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target m68k-none-eabi --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "m68k-none-eabi". Use `--print target-list` for a list of built-in targets

Error: command ["cargo", "build", "--manifest-path", "/rust-mega-drive/examples/megapong/Cargo.toml", "-Z", "unstable-options", "-Z", "build-std=core", "--profile", "release", "--target", "m68k-none-eabi", "-v"] exited with code 101
```

And when I retarget to `m68k-unknown-linux-gnu`, it throws a different error:
```
LLVM ERROR: Cannot select: t51: ch = store<(volatile store 2 into `i16* bitcast (i8* getelementptr inbounds (<{ [4 x i8] }>, <{ [4 x i8] }>* @_ZN13megadrive_sys3vdp3VDP12set_addr_raw7SCRATCH17hc4929cfeef29e122E, i32 0, i32 0, i32 2) to i16*)`, !noalias !102)> t47, Constant:i16<128>, t50, undef:i32
  t48: i16 = Constant<128>
  t50: i32 = add nuw t60, Constant:i32<2>
    t60: i32 = M68kISD::WrapperPC TargetGlobalAddress:i32<<{ [4 x i8] }>* @_ZN13megadrive_sys3vdp3VDP12set_addr_raw7SCRATCH17hc4929cfeef29e122E> 0
      t59: i32 = TargetGlobalAddress<<{ [4 x i8] }>* @_ZN13megadrive_sys3vdp3VDP12set_addr_raw7SCRATCH17hc4929cfeef29e122E> 0
    t49: i32 = Constant<2>
  t3: i32 = undef
In function: main
error: could not compile `megapong`

Caused by:
  process didn't exit successfully: `rustc --crate-name megapong --edition=2018 examples/megapong/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C metadata=7266d68b5d07812a -C extra-filename=-7266d68b5d07812a --out-dir /rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps --target m68k-unknown-linux-gnu -L dependency=/rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps -L dependency=/rust-mega-drive/target/release/deps --extern 'noprelude:compiler_builtins=/rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps/libcompiler_builtins-c405a5e1ad161fe0.rlib' --extern 'noprelude:core=/rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps/libcore-c5d1af975ca618e4.rlib' --extern megadrive_graphics=/rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps/libmegadrive_graphics-d70c4824c86f2739.rlib --extern megadrive_input=/rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps/libmegadrive_input-e98b333c973f8527.rlib --extern megadrive_sys=/rust-mega-drive/target/m68k-unknown-linux-gnu/release/deps/libmegadrive_sys-7b4b56a4c7f9d40d.rlib -Z unstable-options` (exit code: 101)
Error: command ["cargo", "build", "--manifest-path", "/rust-mega-drive/examples/megapong/Cargo.toml", "-Z", "unstable-options", "-Z", "build-std=core", "--profile", "release", "--target", "m68k-unknown-linux-gnu", "-v"] exited with code 101
```

So I'm a little bit confuzzled on how you got this to compile...

**Comment by ricky26** [comment]
That json file is a rust target definition, you can point to it instead of a builtin target. The name should be fine, it has to be different to the builtin targets anyway. This is one of the things that the megadrive cargo plugin is supposed to do for you, so I'm not entirely sure why that's not working.

Actually, I think you just need to point `MEGADRIVE_HOME` to the share directory. Yet another documentation bug. :sweat_smile:

**Comment by reinvantveer** [comment]
Ohhhhhh it compiled. Let's see what it made.

**Comment by reinvantveer** [comment]
Ohohoh my goodness
image
It worked!!! Wow, what a time to be alive!

**Comment by ricky26** [comment]
Awesome! Hope you enjoy megapong! :joy: 

Thanks for following this through to the end, it was a much rockier road than I expected.

**Pull request merged**
